#pragma once

#define USE_SERIAL

#define EE_HANDS

#undef RGBLED_NUM
#define RGBLED_NUM 12
#undef RGBLED_SPLIT
#define RGBLIGHT_SLEEP
#define RGBLIGHT_LAYERS

#define OLED_BRIGHTNESS 128
#define OLED_DISPLAY_128X64